import { default as _ActionsPanelMobileServiceBtnView } from './ActionsPanelMobileServiceBtnView'
const ActionsPanelMobileServiceBtnView = _ActionsPanelMobileServiceBtnView
export default ActionsPanelMobileServiceBtnView
